plugins:
  - stylelint-scss
  - stylelint-order
syntax:
  - scss
rules:
  at-rule-no-unknown: null
  scss/at-rule-no-unknown: true
  string-quotes: single
  selector-no-vendor-prefix: true
  selector-attribute-quotes: never
  property-no-vendor-prefix: true
  no-descending-specificity: null
  media-feature-name-no-vendor-prefix: true
  value-no-vendor-prefix: true
  'order/properties-alphabetical-order': true
